### ISSUE TITLE
App setup instructions

### ISSUE THREAD

**Issue by PJonestown** [AnthonyBobsin/techether#2]
I've been trying for the past hour or two and just can't get it working. Running into lots of pain with the missing database.yml, devise.rb, and secrets.yml files. 

I'm not sure whether this is an issue with my inexperience, the app's documentation, or if this app is unnecessarily locked down. I've forked and used mysql + devise projects before and had no issue, but it could have been that those people didn't take the correct precautions when open sourcing their projects.

**Comment by AnthonyBobsin** [comment]
I apologize, I totally forgot that I included those files in my .gitignore. That is completely my fault. I did that in the first place to hide the production database credentials from the general public but didn't take into account that it would cause problems for others. I am going to start looking into finding a work around for this without giving people access to the production database. I will give you an update when I figure something out but please let me know if you have any recommendations on going about this issue.

**Comment by AnthonyBobsin** [comment]
Have you tried creating your own database.yml file with your own database credentials? Let me know if this doesn't work. Again, I apologize for the inconvenience, I am fairly new to this.

**Comment by PJonestown** [comment]
All good man. I just figured it out. I'm new too, so this may be obvious to more experienced guys, but here's the steps I took to get everything working correctly:

$ touch config/databse.yml

```yaml
common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password:
  host: '127.0.0.1'

development:
  <<: *common
  database: techether_development

test:
  <<: *common
  database: techether_test
```

Then I commented out all lines referencing devise

config/routes.rb

```ruby
# resources :users, only: [:show]
# devise_for :users, :controllers => { registrations: 'registrations' }
```

app/models/user.rb

```ruby
#   devise :database_authenticatable, :registerable,
#        :recoverable, :rememberable, :trackable, :validatable
```

$ rails g devise:install

Uncomment out the lines

$ rake db:setup

This will give an error for a missing devise secret key. Copy and pasted that key into config/initializers/devise.rb

$touch config/secrets.yml

```yaml
development:
  secret_key_base: **secret key**
```
